import {
  Code, Database, Zap, Globe, Tag, Brain, Sparkles,
  Route, Braces, FileText, Cpu, Target, Layers, Server,
  BarChart2, Sigma, Settings, Crosshair, Hexagon, SlidersHorizontal,
  Gamepad2, ThumbsUp, Image, Repeat, Box, Aperture,
  Bot, Cloud, Plug, Shield, Network, Layout,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const COURSE_ICONS: Record<string, LucideIcon> = {
  python: Code, java: Code, sql: Database, go: Zap,
  javascript: Globe, typescript: Tag,
  'mathematics-for-ai': Brain, 'rag-zero-to-hero': Sparkles,
  'langchain-langgraph': Route, 'introduction-to-pandas': Braces, 'introduction-to-pandas-for-data-analysis': Braces,
  'nlp-fundamentals': FileText,
  'pytorch-fundamentals': Zap,
  'prompt-engineering': FileText,
  'numpy-linear-algebra': Cpu,
  'vector-databases-embeddings': Database,
  'neural-networks-from-scratch': Brain,
  'fine-tuning-llms': Target,
  'data-visualization': BarChart2,
  'statistics-probability': Sigma,
  'scikit-learn-masterclass': Settings,
  'supervised-learning': Crosshair,
  'unsupervised-learning': Hexagon,
  'hyperparameter-tuning': SlidersHorizontal,
  'reinforcement-learning': Gamepad2,
  'recommendation-systems': ThumbsUp,
  'cnns-computer-vision': Image,
  'rnns-sequence-models': Repeat,
  'transformers-attention': Box,
  'multimodal-ai': Aperture,
  'ai-agents': Bot,
  'mlops-deployment': Cloud,
  'ai-api-design': Plug,
  'ai-safety-alignment': Shield,
  'microservices': Network,
  'ml-system-design': Layers,
  'concurrency-interview': Cpu,
  'lld': Braces,
  'system-design-interviews': Layout,
};

export const COURSE_COLORS: Record<string, string> = {
  python: '#3572A5', java: '#b07219', sql: '#e38c00', go: '#00ADD8',
  javascript: '#f1e05a', typescript: '#3178c6',
  'mathematics-for-ai': '#a855f7', 'rag-zero-to-hero': '#06b6d4',
  'langchain-langgraph': '#ff6b35', 'introduction-to-pandas': '#e91e8c', 'introduction-to-pandas-for-data-analysis': '#e91e8c',
  'nlp-fundamentals': '#10b981',
  'pytorch-fundamentals': '#ee4c2c',
  'prompt-engineering': '#6366f1',
  'numpy-linear-algebra': '#4dabcf',
  'vector-databases-embeddings': '#14b8a6',
  'neural-networks-from-scratch': '#f97316',
  'fine-tuning-llms': '#7c3aed',
  'data-visualization': '#0ea5e9',
  'statistics-probability': '#8b5cf6',
  'scikit-learn-masterclass': '#f97316',
  'supervised-learning': '#ef4444',
  'unsupervised-learning': '#14b8a6',
  'hyperparameter-tuning': '#ec4899',
  'reinforcement-learning': '#f59e0b',
  'recommendation-systems': '#22c55e',
  'cnns-computer-vision': '#3b82f6',
  'rnns-sequence-models': '#a855f7',
  'transformers-attention': '#06b6d4',
  'multimodal-ai': '#d946ef',
  'ai-agents': '#f97316',
  'mlops-deployment': '#6366f1',
  'ai-api-design': '#10b981',
  'ai-safety-alignment': '#ef4444',
  'microservices': '#0ea5e9',
  'ml-system-design': '#a855f7',
  'concurrency-interview': '#f59e0b',
  'lld': '#ec4899',
  'system-design-interviews': '#14b8a6',
};

export const CATEGORY_META: Record<string, { icon: LucideIcon }> = {
  'All': { icon: Layers },
  'Programming Languages': { icon: Code },
  'AI & Machine Learning': { icon: Cpu },
  'Data & Databases': { icon: Database },
  'DevOps': { icon: Server },
  'Interview Prep': { icon: Target },
  'System Design': { icon: Layout },
  'Product Management': { icon: Target },
};
